In [1]:
import numpy as np

In [2]:
print(np.__version__)

1.18.5


In [3]:
x = [2, 3, 4, 5, 6]
nums = np.array([2, 3, 4, 5, 6])
type(nums)

numpy.ndarray

In [4]:
#1D array
arr = np.arange(10)
arr
#> array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
#2d array
b = np.arange(12).reshape(4,3)           
print(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
