# Assignment No: 1

# Name    :   khalil ur rehman
# Roll no  :  PIAIC131403

In [ ]:
 import numpy as np

In [6]:
print(np.__version__)

1.18.5


# 50 numpy methods

In [86]:
#1
a=np.arange(15,40)
a

array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
       32, 33, 34, 35, 36, 37, 38, 39])

In [4]:
#2 one dimentional array
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
#3 item size
a = np.array([1,2,3])
print(a.itemsize)

4


In [5]:
#4
b = np.arange(12).reshape(4,3)           
print(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [8]:
#5 Numpy Operation
a = np.array([(1,2,3),(4,5,6)])
print(a.ndim)

2


In [21]:
#6 numpy mutidimentional array
x = [2, 3, 4, 5, 6]
nums = np.array([2, 3, 4, 5, 6])
type(nums)

numpy.ndarray

In [87]:
#7 data type
a = np.array([(1,2,3)])
print(a.dtype)

int32


In [10]:
#8 size of array
a=np.array([1,2,3,4])
print(a.size)

4


In [13]:
#9 shape of array
a = np.array([3,4,5,4])
print(a.shape)

(4,)


In [19]:
#10 reshape of array
a = np.array([(1,5,3),(6,8,7)])
print(a)

a = a.reshape(3,2)
print(a)

[[1 5 3]
 [6 8 7]]
[[1 5]
 [3 6]
 [8 7]]


In [20]:
#11 Boolean Array
bool_arr = np.array([1, 0.5, 0, None, 'a', '', True, False], dtype=bool)
print(bool_arr)

[ True  True False False  True False  True False]


In [25]:
#12 Square Root
a = np.array([(1,2,3),(4,5,6)])
print(np.sqrt(a))

[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]


In [26]:
#13 Standard Division
a = np.array([(1,2,3),(4,5,6)])
print(np.std(a))

1.707825127659933


In [27]:
#14 zero numpy array
array1d = np.zeros(3)
print(array1d)

[0. 0. 0.]


In [28]:
#15 Vertical stacking
a = np.array([(1,2,3),(4,5,6)])
b = np.array([(1,2,3),(4,5,6)])
print(np.vstack((a,b)))

[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]


In [33]:
#16 horizontal Stacking
a = np.array([(1,2,3),(4,5,6)])
b = np.array([(1,2,3),(4,5,6)])
print(np.hstack((a,b)))

[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]


In [38]:
#17 generate random number
print(np.random.rand(3, 3))

[[0.79267083 0.82972502 0.39052986]
 [0.01015034 0.18828172 0.45868911]
 [0.95571506 0.82369471 0.7275105 ]]


In [40]:
#18 normally distributed value
print(np.random.randn(3, 2))

[[-1.3135772   0.49415092]
 [-0.211857    0.76722515]
 [ 1.16667769 -1.00188944]]


In [41]:
#19 Adding Operation
a = np.array([(1,2,3),(4,5,6)])
b = np.array([(1,2,3),(4,5,6)])
print(a+b)

[[ 2  4  6]
 [ 8 10 12]]


In [88]:
#20 Subtraction
a = np.array([(1,2,3),(4,5,6)])
b = np.array([(1,2,3),(4,5,6)])
print(a-b)

[[0 0 0]
 [0 0 0]]


In [89]:
#21 Multiplication
a = np.array([(1,2,3),(4,5,6)])
b = np.array([(1,2,3),(4,5,6)])
print(a*b)

[[ 1  4  9]
 [16 25 36]]


In [90]:
#22 Division
a = np.array([(1,2,3),(4,5,6)])
b = np.array([(1,2,3),(4,5,6)])
print(a/b)

[[1. 1. 1.]
 [1. 1. 1.]]


In [43]:
#23 time function
a = np.arange(10000000)
a
%time

Wall time: 0 ns


In [45]:
#24 converting 2-D into 1-D array
a = np.array([(4,5,6),(8,9,10)])
a = a.flatten()
a

array([ 4,  5,  6,  8,  9, 10])

In [46]:
#25 Ravel
x= np.array([(1,2,3),(3,4,5)])
print(x.ravel())

[1 2 3 3 4 5]


In [47]:
#26 converting an array to a list
a = np.array([(1,2,3),(4,5,6)])
a = a.tolist()
a

[[1, 2, 3], [4, 5, 6]]

In [49]:
#27 Repeat elements of an array
import numpy as np
x = np.repeat(3, 4)
print(x)
x = np.array([[1,2],[3,4]])
print(np.repeat(x, 2))

[3 3 3 3]
[1 1 2 2 3 3 4 4]


In [52]:
#28 union of two arrays
array1 = np.array([2, 15, 10, 44, 20, 40])
print("Ar1: ",array1)
array2 = [12, 40, 20, 10, 20]
print("Ar2: ",array2)
print("Unique sorted array of values that are in either of the two input arrays:")
print(np.union1d(array1, array2))

Ar1:  [ 2 15 10 44 20 40]
Ar2:  [12, 40, 20, 10, 20]
Unique sorted array of values that are in either of the two input arrays:
[ 2 10 12 15 20 40 44]


In [53]:
#29 set difference of two arrays
array1 = np.array([2, 15, 10, 44, 20, 40])
print("Ar1: ",array1)
array2 = [12, 40, 20, 10, 20]
print("Ar2: ",array2)
print("Unique values in array1 that are not in array2:")
print(np.setdiff1d(array1, array2))

Ar1:  [ 2 15 10 44 20 40]
Ar2:  [12, 40, 20, 10, 20]
Unique values in array1 that are not in array2:
[ 2 15 44]


In [55]:
#30 creating an array having all values of zeros
import numpy as np
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [57]:
#31 creating a 4x4 diagnol array
a = np.eye(4)
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [59]:
#32  3 x 3 array with all values one
a = np.full((3,3),1)
a

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [60]:
#33 transpose of 2x3 to 3x2 array
a = np.array([1,2,3,4,5,6])
a = a.reshape((2,3))
a = a.T
a

array([[1, 4],
       [2, 5],
       [3, 6]])

In [63]:
#34 for maximum value
b = np.array([40,34,56,43])
b = np.max(b)
b

56

In [65]:
#35 for minimum value
a = np.array([40,33,56,43])
a = np.min(a)
a

33

In [91]:
#36 slicing
a=np.array([(1,2,3,4),(3,4,5,6)])
print(a[0:,2])

[3 5]


In [67]:
#37 2D array of shape 3x4 to contain decimal numbers between 1 and 12
arr2D = np.arange(1,13,dtype='float').reshape(3,4)
arr2D

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.]])

In [68]:
#38 dot product of 2 matrix
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])
np.dot(x,y)

array([[ 28.,  64.],
       [ 67., 181.]])

In [71]:
#38 Odd number
arr1 =np.array(range(12)) 
for i in arr1:
    if i%2==1:
        print(i)

1
3
5
7
9
11


In [70]:
#39 Even Number
arr1 =np.array(range(12)) 
for i in arr1:
    if i%2==0:
        print(i)

0
2
4
6
8
10


In [73]:
#40 Replace one value to another
arr2d = np.array([[1, 2, 3],[4, 5, 6], [7, 8, 9]])
arr2d[1,2] =  15  
print(arr2d)
arr2d.ndim

[[ 1  2  3]
 [ 4  5 15]
 [ 7  8  9]]


2

In [74]:
#41 Convert 1-D arrays as columns into a 2-D array
a = np.array((10,20,30))
b = np.array((40,50,60))
c = np.column_stack((a, b))
print(c)

[[10 40]
 [20 50]
 [30 60]]


In [75]:
#42 Get the number of nonzero elements in an array
x = np.array([[0, 10, 20], [20, 30, 40]])
print("Original array:")
print(x)
print("Number of non zero elements in the above array:")
print(np.count_nonzero(x))

Original array:
[[ 0 10 20]
 [20 30 40]]
Number of non zero elements in the above array:
5


In [76]:
#43 repeating the elements in array for sequences 2
a=np.array([1, 2, 3, 4, 5, 6, 7, 8])
np.r_[np.tile(a, 6)]

array([1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 3, 4, 5, 6,
       7, 8, 1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 3, 4,
       5, 6, 7, 8])

In [78]:
#44 getting comon elements from two different arrays
a = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16])
b = np.array([1,3,5,7,9,11,13,15,17,19])
np.intersect1d(a,b)

array([ 1,  3,  5,  7,  9, 11, 13, 15])

In [79]:
#45  swaping columns in 2darray
arr=np.arange(9).reshape(3,3)
arr[:,[1,0,2]]

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

In [81]:
#46 How to calculate mean value
b = np.array([10,3,5,2,1,7,3,4,0,1,5,25,8,20,12,11])
np.mean(b)

7.3125

In [82]:
#47 how to calculate median
b = np.array([10,3,5,2,1,7,3,4,0,1,5,25,8,20,12,11])
np.median(b)

5.0

In [83]:
#48 addition of a specific value in each array element
b = np.array([4,8,6,2,5,15])
a = np.add(b,7)
a

array([11, 15, 13,  9, 12, 22])

In [84]:
#49 taking square root of each element in an array
a = np.array([1,7,8,4,9,10,16,25])
a = np.sqrt(a)
a

array([1.        , 2.64575131, 2.82842712, 2.        , 3.        ,
       3.16227766, 4.        , 5.        ])

In [85]:
#50 absolute value of elements in an array
a = np.array([1.01200000,1.600,1.503000,1.4120])
a = np.abs(a)
a

array([1.012, 1.6  , 1.503, 1.412])